### ISSUE TITLE
Exeption error when player tries to list something for sale.

### ISSUE THREAD

**Issue by Klawdek** [badbones69/Crazy-Auctions#108]
**Describe the bug**
When player tries to put an item for sale an error occurs in console.  This just started happeneing it was working fine before.  No changes were made to config file before error started happening.

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.8.8]  1.15.2
 - Plugin Version: [e.g. 1.2.12] CrazyAuctions version 1.2.12-RELEASE
Paper version git-Paper-251 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
*Do **NOT** say Latest use `/version crazyauctions` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/
https://pastebin.com/WSKQDcUy
**Issue**
Describe the issue you are having with the plugin.

**Screenshots**

**Comment by Klawdek** [comment]
UPDATE:  THIS BUG CAN BE USED TO DUPE ITEMS!  it seems if players do prices of 99998 or less it works.  If they do 99999 or more the exception happens.  And the item is still put on auction but not removed from player inventory, so this can be used to dupe items by cancelling and getting back the item.

**Comment by Klawdek** [comment]
Further update:  While typing the above several players that had never joined my server came on and massively duped items.  They got large sums of money and 2nd tier currency from crates by duping crate keys and then gave large amount of money to other players thus messing up the economy of the server.  I have removed the Crazy Auctions from my server.

**Comment by NeedNot** [comment]
May I ask what server you own?

**Comment by NeedNot** [comment]
I might know the issue and it can be fixed very easily

**Comment by Klawdek** [comment]
> May I ask what server you own?
The server you and SuazTwist and a few others trashed yesterday.

**Comment by NeedNot** [comment]
> UPDATE: THIS BUG CAN BE USED TO DUPE ITEMS! it seems if players do prices of 99998 or less it works. If they do 99999 or more the exception happens. And the item is still put on auction but not removed from player inventory, so this can be used to dupe items by cancelling and getting back the item.

hint that's not the dupe

**Comment by bartyrealms** [comment]
I was just banned for reporting this bug in the Discord, but there is more to it than selling for 999999. I cannot report the bug now that I am banned, and do not wish to make it public.

**Comment by RyderBelserion** [comment]
You weren't banned for reporting the bug, The developer of the plugin is not even able to replicate it even with the help review.

The Dupe Bugs are irrelevant when the plugin is under re-coding and all bugs will be fixed in that version and more also yes control your player-base as its your player-base and your in charge of what happens to them when they do things like this. You can grab the re-coded version when its completed as I don't think the old one is going to be updated anymore anyway as its obsolete now.

https://www.spigotmc.org/resources/auctionhouse-legacy.66670/

Use this if its a problem, Bye.

**Comment by bartyrealms** [comment]
> 
> 
> You weren't banned for reporting the bug.
> 
> The Dupe Bugs are irrelevant when the plugin is under re-coding and all bugs will be fixed in that version and more also yes control your player-base as its your player-base and your in charge of what happens to them when they do things like this. You can grab the re-coded version when its completed as I don't think the old one is going to be updated anymore anyway as its obsolete now.

This is just a bad way to go about things. For now, blacklisting written books seems to work and there is a PR sitting there requesting to add it to the default blacklist. I see no reason to let it sit nor care about dupe bugs when they can have a large impact on the servers using this plugin. Please unban me.

**Comment by theminecoder** [comment]
> The Dupe Bugs are irrelevant
This may be the case to you while you are in the mindset of "I'm making some new, so everything will be fine once that's but" however you are leaving servers open to abuse in the meantime while the new plugin isn't out which puts a bad reputation on you as a developer/team/whatever.

This is a **critical** issue that should be fixed in the mean time otherwise people will have to stop recommending your plugin over time as their servers are abused.

**Comment by RyderBelserion** [comment]
You may not like it but why would a dev if he making a newly recoded version from scratch spend time applying fixes to an older outdated and bugged version? That does not make sense and you can thumbs me down all you want. Its the same as SavageFactions being abandoned and not getting fixes while a new plugin is being made contains all the fixes. Its how it works and has always worked. 

The plugin is open source and you can get someone to update it if you so wish to but I wouldn't expect BadBones to do it. There is a reason he made a new branch and wiped all the old code. He not going to update it.

**Comment by bartyrealms** [comment]
> 
> 
> You may not like it but why would a dev if he making a newly recoded version from scratch spend time applying fixes to an older outdated and bugged version? That does not make sense and you can thumbs me down all you want. Its the same as SavageFactions being abandoned and not getting fixes while a new plugin is being made that contains all the fixes and much better code. Its how it works and has always worked.
> 
> The plugin is open source and you can get someone to update it if you so wish to but I wouldn't expect BadBones to do it. There is a reason he made a new branch and wiped all the old code. He not going to update it.

We have already fixed it on our server but you are also laying out thousands of servers out to dry and basically saying "tough shit". Banning people who have differing opinions on this doesn't make you look any better. Why would anyone use this plugin in the future if this is how you treat people? Thousands of servers are now sitting with a pretty bad dupe bug thanks to your plugin and your response is "control your players"? Seriously?

**Comment by RyderBelserion** [comment]
I am not even the person who banned you, I am saying it how it is and how a developer works. If the fix is as simple as adding "WRITTEN_BOOK",  Surely thousands of servers can figure that out and not have to require an update or be told by the developer for it. There is a reason its a configurable list of items you can block and not a hard coded value. Its called a 24/7 bandaid built in for reports like this to hold people off until he has time to sit down and finish the recode.

**Comment by bartyrealms** [comment]
> 
> 
> I am not even the person who banned you, I am saying it how it is and how a developer works. If the fix is as simple as adding "WRITTEN_BOOK", Surely thousands of servers can figure that out and not have to require an update or be told by the developer for it. There is a reason its a configurable list of items you can block and not a hard coded value. Its called a 24/7 bandaid built in for reports like this to hold people off until he has time to sit down and finish the recode.

We were told to expect a fix "within the year". That's ridiculous. That is not how most developers in this community act, especially ones who maintain very popular plugins such as this one. I really hope you do not speak for the maintainer of this plugin.

We were holding off on reporting the plugin public because we don't want to publicize it but the fact that we were banned for attempting to report it is **ridiculous**.

**Comment by RyderBelserion** [comment]
I also not the person that told you a fix within a year, I highly doubt BadBones will take a year to rewrite this plugin.

I'd say a potential week or two max as he has a job, he has 7 other plugins he has to manage on top of that and whatever else he does outside those 2 things. The one that said "Within a year" is not a developer and is also not BadBones69. You are unbanned as that is excessive for at least the logs I saw also I'd recommend omitting your email. Hito can bother me as to why you are unbanned. If anything else happens with you then I'll just take responsibility.

**Comment by Yukun99** [comment]
I'm a former server owner that knows how painful it is when a plugin you've used for a long time stops working or as bugs. I know how you feel. However, many of you really do need to realise that developers do have a life outside of making plugins on spigot. In fact, most of us do this because we want to see people use our plugins and have fun with them. However, that does not mean that we can or will use all of our spare time on this, that's simply a recipe for disaster. Besides, there is already a recode in the works, and after badbones ends his super busy covid shifts, he's already trying his best to get to work. (Not to mention 10 or so staff and 20 or so donors already bug him pretty often to update his stuff.) Ryder may not be the most tactful staff member, but what he's trying to say is to simply be patient and wait for the better update to come.

Which brings me to my next point. As a spigot developer as well, I know just as well the pain that badbones goes through to provide support for 7 HUGE plugins. In fact, he has tried providing support for older code while doing recodes, and it didn't work out well for CE and ended up delaying the release of the recoded version for months. He is simply trying to let the perfected version come out sooner this time by making the old version effectively deprecated. Insisting on support now will just delay the better version coming soon, with haphazard fixes thrown into the plugin in the meantime that further slow development down.

And now moving on to the final point about why you were banned. You were not banned for reporting the bug, you were banned because an admin who was trying to help you told you what the situation was and you got impatient, leading to bad attitude and spamming of tags against him. Granted, that may be a pretty low bar for banning or kicking someone from the server, and that's why you're unbanned now. However, it'd be nice if anyone who seeks support from now on treats the staff with the same respect that you expect from them and for god's sake, just have some patience. We all have lives outside of spigot, and we're all here because we like helping, or because we want to help badbones. We do not have the time nor the obligation to be here 24/7, jumping on every message you send us or tag us in.

Hope you understand and continue to support badbones in his years-long coding adventure.

**Comment by Yukun99** [comment]
You can keep downvoting staff replies all you like, but I don't see you refuting any of my points properly. As it stands, you tagged a staff multiple points, which is really annoying. Hope you've learnt not to do that anymore. We've told you how the plugin will be progressing from this point forward. I can't help you any further than this. You may think all large plugins all have clean code and don't need much work between updates, but BB never planned for this to be this big, and he wasn't doing things cleanly at the start. So if you want to have anything even remotely good, I'd suggest waiting for the completed recode, and not bugging him for more updates on the old version. Burnout is real and pretty sure no one wants BB to go through that.

**Comment by MrAureliusR** [comment]
Wow, glad to know the developers of this plugin don't care about the servers that use it at all.
Why would you update the plugin? It's called supporting your customer base. If you want people to support you and use your plugins, you need to support them, even with a new product coming. This is business 101 stuff, come on.

Deleting this plugin from our server, and recommending every other server owner I know to stay WAY away from this dev and their plugins.

**Comment by RyderBelserion** [comment]
And it is being addressed by recoding the entire plugin and making a new version of it? Is that not getting through your head? That's what BadBones is doing. He is doing everything in CrazyAuctions from scratch and will release that on Spigot when its ready.

**Comment by badbones69** [comment]
This is being fixed before the recode is posted. I have been able to replicate the error and will be working on a fix.

**Comment by badbones69** [comment]
This has been fixed and there is now a character limit of 2k for all written and writable books.
4e11b2b3024e793dfc20d451e25ab8594cf93652
